// {
//   badge:false,
//   badgetype:"",
//   sconto:0,
//   linkimmagine:"",
//   titolo:"",
//   rating:0,
//   prezzo:0,
//   linkprodotto:"",
//   onClick:"",
// }

 let apiDummy =[
  [
    //Random 
    {
      badge:false,
      badgetype:"",
      sconto:0,
      linkimmagine:"https://www.lego.com/cdn/cs/set/assets/blt10c72e2ab2785ea4/10306.png?fit=bounds&format=webply&quality=80&width=320&height=320&dpr=1.5",
      titolo:"Atari 2600",
      rating:4,
      prezzo:(239.99),
      linkprodotto:"",
      onClick:"",
    },
    {
      badge:true,
      badgetype:"Novità",
      sconto:0,
      linkimmagine:"https://www.lego.com/cdn/cs/set/assets/blt36fb03cdeb25ad1a/10302.png?fit=bounds&format=webply&quality=80&width=320&height=320&dpr=1.5",
      titolo:"Optimus Prime",
      rating:3,
      prezzo:(179.99),
      linkprodotto:"",
      onClick:"",
    },
    {
      badge:true,
      badgetype:"Difficile da trovare",
      sconto:20,
      linkimmagine:"https://www.lego.com/cdn/cs/set/assets/blt0254ea3dce736ea0/10305.png?fit=bounds&format=webply&quality=80&width=320&height=320&dpr=1.5",
      titolo:"Castello dei cavalieri del leone",
      rating:3.5,
      prezzo:(399.99),
      linkprodotto:"",
      onClick:"",
    },
    {
      badge:false,
      badgetype:"",
      sconto:0,
      linkimmagine:"https://www.lego.com/cdn/cs/set/assets/blt15246c4306d1f236/76161.jpg?fit=bounds&format=webply&quality=80&width=320&height=320&dpr=1.5",
      titolo:"Batwing",
      rating:5,
      prezzo:(199.99),
      linkprodotto:"",
      onClick:"",
    },
    {
      badge:true,
      badgetype:"Esclusivo",
      sconto:0,
      linkimmagine:"https://www.lego.com/cdn/cs/set/assets/blt6007d8f29092bb5f/75340_alt1.png?fit=bounds&format=webply&quality=80&width=320&height=320&dpr=1.5",
      titolo:"Calendario dell'avvento di Star Wars",
      rating:3,
      prezzo:(34.99),
      linkprodotto:"",
      onClick:"",
    },
    {
      badge:true,
      badgetype:"Difficile da trovare",
      sconto:10,
      linkimmagine:"https://www.lego.com/cdn/cs/set/assets/bltc6d87e5e7bacb3ae/21333.png?fit=bounds&format=webply&quality=80&width=320&height=320&dpr=1.5",
      titolo:"Vincent Van Gogh - Notte Stellata",
      rating:5,
      prezzo:(169.99),
      linkprodotto:"",
      onClick:"",
    },
    {
      badge:true,
      badgetype:"Il più amato",
      sconto:20,
      linkimmagine:"https://www.lego.com/cdn/cs/set/assets/blt497da03153fb9a10/21319.jpg?fit=bounds&format=webply&quality=80&width=320&height=320&dpr=1.5",
      titolo:"Central Perk",
      rating:5,
      prezzo:(299.99),
      linkprodotto:"",
      onClick:"",
    },
    {
      badge:true,
      badgetype:"Nuovo",
      sconto:0,
      linkimmagine:"https://www.lego.com/cdn/cs/set/assets/bltd6f8047eaa1d3a3a/76206.png?fit=bounds&format=webply&quality=80&width=320&height=320&dpr=1.5",
      titolo:"Personaggio di Iron Man",
      rating:4.5,
      prezzo:(39.99),
      linkprodotto:"",
      onClick:"",
    }
  ],
  [
    //Random2
    {
      badge:true,
      badgetype:"Novità",
      sconto:0,
      linkimmagine:"https://www.lego.com/cdn/cs/set/assets/blt36fb03cdeb25ad1a/10302.png?fit=bounds&format=webply&quality=80&width=320&height=320&dpr=1.5",
      titolo:"Optimus Prime",
      rating:3,
      prezzo:(179.99),
      linkprodotto:"",
      onClick:"",
    },
    {
      badge:false,
      badgetype:"",
      sconto:30,
      linkimmagine:"https://www.lego.com/cdn/cs/set/assets/blt0e81d1708c094553/10303.png?fit=bounds&format=webply&quality=80&width=320&height=320&dpr=1.5",
      titolo:"Montagne Russe",
      rating:5,
      prezzo:(209.99),
      linkprodotto:"",
      onClick:"",
    },
    {
      badge:true,
      badgetype:"Difficile da trovare",
      sconto:0,
      linkimmagine:"https://www.lego.com/cdn/cs/set/assets/blt62f99776b13a8e94/10297.png?fit=bounds&format=png&width=320&height=320&dpr=3",
      titolo:"Boutique",
      rating:5,
      prezzo:(169.99),
      linkprodotto:"",
      onClick:"",
    },
    {
      badge:false,
      badgetype:"",
      sconto:10,
      linkimmagine:"https://www.lego.com/cdn/cs/set/assets/blt1cedf079c8ffbe5e/42130_Prod.png?fit=bounds&format=png&width=320&height=320&dpr=3",
      titolo:"BMW M1000",
      rating:4,
      prezzo:(79,99),
      linkprodotto:"",
      onClick:"",
    },
    {
      badge:true,
      badgetype:"Difficile da trovare",
      sconto:0,
      linkimmagine:"https://www.lego.com/cdn/cs/set/assets/blt6e4605758d75ce41/31203.jpg?fit=bounds&format=jpg&quality=80&width=320&height=320&dpr=3",
      titolo:"Mappa del Mondo",
      rating:5,
      prezzo:(169.99),
      linkprodotto:"",
      onClick:"",
    },
    {
      badge:true,
      badgetype:"Il più forte",
      sconto:20,
      linkimmagine:"https://www.lego.com/cdn/cs/set/assets/blt729f7a96490ebf6f/10304.png?fit=bounds&format=png&width=320&height=320&dpr=2",
      titolo:"Batmobile di Batman",
      rating:5,
      prezzo:(159.99),
      linkprodotto:"",
      onClick:"",
    },
    {
      badge:true,
      badgetype:"Idea regalo",
      sconto:0,
      linkimmagine:"https://www.lego.com/cdn/cs/set/assets/blt505d24ad41366851/21327.jpg?fit=bounds&format=jpg&quality=80&width=320&height=320&dpr=3",
      titolo:"Macchina da Scrivere",
      rating:5,
      prezzo:(299.99),
      linkprodotto:"",
      onClick:"",
    },
    {
      badge:false,
      badgetype:"",
      sconto:0,
      linkimmagine:"https://www.lego.com/cdn/cs/set/assets/blt9ecbcfc462381676/71040.jpg?fit=bounds&format=jpg&quality=80&width=320&height=320&dpr=1",
      titolo:"Il castello Disney",
      rating:5,
      prezzo:(399.99),
      linkprodotto:"",
      onClick:"",
    },
  ],
  [
    //Marvel
    {
      badge:true,
      badgetype:"SNAP!",
      sconto:0,
      linkimmagine:"https://www.lego.com/cdn/cs/set/assets/blt094ad51f69e44f8f/76223.png?fit=bounds&format=webply&quality=80&width=320&height=320&dpr=1.5",
      titolo:"Guanto dell'Infinito di Iron Man",
      rating:4.5,
      prezzo:(69.99),
      linkprodotto:"",
      onClick:"",
    },
    {
      badge:true,
      badgetype:"Tra i più amati",
      sconto:30,
      linkimmagine:"https://www.lego.com/cdn/cs/set/assets/bltd22f99034387c7ac/76209.png?fit=bounds&format=webply&quality=80&width=320&height=320&dpr=1.5",
      titolo:"Il martello di Thor",
      rating:4,
      prezzo:(199.99),
      linkprodotto:"",
      onClick:"",
    },
    {
      badge:true,
      badgetype:"Esaurito ovunque",
      sconto:0,
      linkimmagine:"https://www.lego.com/cdn/cs/set/assets/blt5157080434f0c032/76218.png?fit=bounds&format=webply&quality=80&width=320&height=320&dpr=1.5",
      titolo:"Sancta Santorum",
      rating:5,
      prezzo:(289.99),
      linkprodotto:"",
      onClick:"",
    },
    {
      badge:false,
      badgetype:"",
      sconto:0,
      linkimmagine:"https://www.lego.com/cdn/cs/set/assets/blte9c486327506d9fb/76210.png?fit=bounds&format=webply&quality=80&width=320&height=320&dpr=1.5",
      titolo:"Hukbuster",
      rating:5,
      prezzo:(229.99),
      linkprodotto:"",
      onClick:"",
    },
    {
      badge:true,
      badgetype:"Novità",
      sconto:0,
      linkimmagine:"https://www.lego.com/cdn/cs/set/assets/blt786d9a5e1bafd414/76217.png?fit=bounds&format=webply&quality=80&width=320&height=320&dpr=1.5",
      titolo:"Io sono Groot",
      rating:4.5,
      prezzo:(49.99),
      linkprodotto:"",
      onClick:"",
    },
    {
      badge:true,
      badgetype:"Super Offerta",
      sconto:50,
      linkimmagine:"https://www.lego.com/cdn/cs/set/assets/blt149a36e6328fd9a8/76178.jpg?fit=bounds&format=webply&quality=80&width=320&height=320&dpr=1.5",
      titolo:"Daily Bugle",
      rating:3.5,
      prezzo:(299.99),
      linkprodotto:"",
      onClick:"",
    },
    {
      badge:false,
      badgetype:"",
      sconto:0,
      linkimmagine:"https://www.lego.com/cdn/cs/set/assets/bltdaa3c3d3679b4432/31199.jpg?fit=bounds&format=webply&quality=80&width=320&height=320&dpr=1.5",
      titolo:"Iron Man - Marvel Studios",
      rating:5,
      prezzo:(99,99),
      linkprodotto:"",
      onClick:"",
    },
    {
      badge:true,
      badgetype:"Il più amato ",
      sconto:10,
      linkimmagine:"https://www.lego.com/cdn/cs/set/assets/blt6c32537ba11c66d2/76193.png?fit=bounds&format=webply&quality=80&width=320&height=320&dpr=1.5",
      titolo:"L'astronave dei Guardiani",
      rating:5,
      prezzo:(169.99),
      linkprodotto:"",
      onClick:"",
    },
  ]
]


// let apiDummy = [
//     
//     
//     [
//       //StarWars
//       {
//         link: "https://www.lego.com/cdn/cs/set/assets/bltdbe9230cce3804cf/75331.png?fit=bounds&format=webply&quality=80&width=320&height=320&dpr=1.5",
//         title: "Razor Crest",
//         price: "599,99",
//         details: "Difficile da trovare",
//         star: "5",
//       },
//       {
//         link: "https://www.lego.com/cdn/cs/set/assets/blt95c35d4ed5665a49/75192.jpg?fit=bounds&format=webply&quality=80&width=320&height=320&dpr=1.5",
//         title: "Millennium Falcon",
//         price: "899,99",
//         details: "Il più veloce",
//         star: "5",
//       },
//       {
//         link: "https://www.lego.com/cdn/cs/set/assets/blt934044fa508776e2/75252.jpg?fit=bounds&format=webply&quality=80&width=320&height=320&dpr=1.5",
//         title: "Imperial Star Destroyer",
//         price: "699,99",
//         details: "Presto fuori catalogo",
//         star: "5",
//       },
//       {
//         link: "https://www.lego.com/cdn/cs/set/assets/blt4be686c9aaced5fa/40547.png?fit=bounds&format=webply&quality=80&width=320&height=320&dpr=1.5",
//         title: "Obi-Wan Kenobi e Darth Vader",
//         price: "19,99",
//         details: "",
//         star: "3",
//       },
//       {
//         link: "https://www.lego.com/cdn/cs/set/assets/blt6007d8f29092bb5f/75340_alt1.png?fit=bounds&format=webply&quality=80&width=320&height=320&dpr=1.5",
//         title: "Calendario dell'Avvento Lego",
//         price: "39,99",
//         details: "",
//         star: "4",
//       },
//       {
//         link: "https://www.lego.com/cdn/cs/set/assets/bltf829afe15b940424/75323.png?fit=bounds&format=webply&quality=80&width=320&height=320&dpr=1.5",
//         title: "The Justifier",
//         price: "179,99",
//         details: "Difficile da trovare",
//         star: "5",
//       },
//       {
//         link: "https://www.lego.com/cdn/cs/set/assets/blt5da3d614bc21e724/5007464.jpg?fit=bounds&format=webply&quality=80&width=320&height=320&dpr=1.5",
//         title: "Pupazzo natalizio di Chewbacca",
//         price: "49,99",
//         details: "Novità",
//         star: "4.5",
//       },
//       {
//         link: "https://www.lego.com/cdn/cs/set/assets/blt09c9288d840d7a7c/40391.jpg?fit=bounds&format=webply&quality=80&width=320&height=320&dpr=1.5",
//         title: "Stormtrooper - Lego Bricks",
//         price: "<p><s>39,99</s> 17,99</p>",
//         details: "",
//         star: "",
//       },
//       {
//         link: "https://www.lego.com/cdn/cs/set/assets/blt7dc15f12b7f8c85f/75288.jpg?fit=bounds&format=webply&quality=80&width=320&height=320&dpr=1.5",
//         title: "At-At",
//         price: "<p><s>239,99</s> 117,99</p>",
//         details: "In offerta",
//         star: "5",
//       },
//     ],
//     [
//       //Lego Friends
//       {
//         link: "https://www.lego.com/cdn/cs/set/assets/blte5547c193bd2c990/41706_alt1.png?fit=bounds&format=webply&quality=80&width=320&height=320&dpr=1.5",
//         title: "Calendario dell'avvento dei Friends",
//         price: "69,99",
//         details: "Esclusivo",
//         star: "4",
//       },
//       {
//         link: "https://www.lego.com/cdn/cs/set/assets/bltb0603f643af7337b/41718.png?fit=bounds&format=webply&quality=80&width=320&height=320&dpr=1.5",
//         title: "Centro Day-Care dei Cuccioli",
//         price: "49,99",
//         details: "",
//         star: "5",
//       },
//       {
//         link: "https://www.lego.com/cdn/cs/set/assets/blt39b342c5659c16cc/41712.png?fit=bounds&format=webply&quality=80&width=320&height=320&dpr=1.5",
//         title: "Camion riciclaggio rifiuti",
//         price: "49,99",
//         details: "",
//         star: "4",
//       },
//       {
//         link: "https://www.lego.com/cdn/cs/set/assets/blteec7162a55c6ce6c/5007274.png?fit=bounds&format=webply&quality=80&width=320&height=320&dpr=1.5",
//         title: "Lunch set Friends",
//         price: "21,99",
//         details: "Nuovo",
//         star: "3",
//       },
//       {
//         link: "https://www.lego.com/cdn/cs/set/assets/blt8db5b8f3cbbaaf53/41709.png?fit=bounds&format=webply&quality=80&width=320&height=320&dpr=1.5",
//         title: "Casa delle vacanze sulla spiaggia",
//         price: "179,99",
//         details: "Difficile da trovare",
//         star: "5",
//       },
//       {
//         link: "https://www.lego.com/cdn/cs/set/assets/bltafb97dd45d3a8d68/41711_WEB_PRI_NOBG.png?fit=bounds&format=webply&quality=80&width=320&height=320&dpr=1.5",
//         title: "La scuola d'arte di Emma",
//         price: "<p><s>139,99</s> 77,99</p>",
//         details: "In Offerta",
//         star: "5",
//       },
//       {
//         link: "https://www.lego.com/cdn/cs/set/assets/blt21da751a48ad5d71/41702.png?fit=bounds&format=webply&quality=80&width=320&height=320&dpr=1.5",
//         title: "Casa Galleggiante",
//         price: "120,99",
//         details: "",
//         star: "4.5",
//       },
//       {
//         link: "https://www.lego.com/cdn/cs/set/assets/bltd8313d0d6209857c/41716.png?fit=bounds&format=webply&quality=80&width=320&height=320&dpr=1.5",
//         title: "Avventura in Barca a Vela",
//         price: "79,99",
//         details: "Novità",
//         star: "3",
//       },
//       {
//         link: "https://www.lego.com/cdn/cs/set/assets/blt5f505a956ed4efb2/41684.jpg?fit=bounds&format=webply&quality=80&width=320&height=320&dpr=1.5",
//         title: "Grand Hotel - City",
//         price: "189,99",
//         details: "",
//         star: "2.5",
//       },
//     ],
//     
//     [ // Nasa
//       {
//         link: "https://www.lego.com/cdn/cs/set/assets/blt3dddc992e5559ddf/21309.jpg?fit=bounds&format=jpg&quality=80&width=320&height=320&dpr=1",
//         title: "Saturn V Apollo LEGO® NASA",
//         price: "199,99",
//         details: "Novità",
//         star: "5",
//       },
//       {
//         link: "https://www.lego.com/cdn/cs/set/assets/blt3777f348d7f98b8d/21321.jpg?fit=bounds&format=jpg&quality=80&width=320&height=320&dpr=1",
//         title: "Stazione Spaziale Internazionale",
//         price: "159,99",
//         details: "Novità",
//         star: "5",
//       },
//       {
//         link: "https://www.lego.com/cdn/cs/set/assets/blt00ba54004c17e820/10283.jpg?fit=bounds&format=jpg&quality=80&width=320&height=320&dpr=1",
//         title: "NASA Space Shuttle Discovery",
//         price: "59,99",
//         details: "Novità",
//         star: "5",
//       },
//       {
//         link: "https://www.lego.com/cdn/cs/set/assets/blt5e2703640ec85d2a/10266.jpg?fit=bounds&format=jpg&quality=80&width=320&height=320&dpr=1",
//         title: "NASA Apollo 11 Lunar Lander",
//         price: "129,99",
//         details: "Novità",
//         star: "4",
//       },
//       {
//         link: "https://www.lego.com/cdn/cs/set/assets/blt15246c4306d1f236/76161.jpg?fit=bounds&format=jpg&quality=80&width=320&height=320&dpr=1",
//         title: "1989 - Batwing",
//         price: "89,99",
//         details: "Il più forte",
//         star: "5",
//       },
//       {
//         link: "https://www.lego.com/cdn/cs/set/assets/blte23f89423d92139d/60350.png?fit=bounds&format=webply&quality=80&width=320&height=320&dpr=1.5",
//         title: "Base di ricerca Lunare",
//         price: "89,99",
//         details: "Novità",
//         star: "5",
//       },
//       {
//         link: "https://www.lego.com/cdn/cs/set/assets/blt4e760d8c14f0cbbe/60351.png?fit=bounds&format=webply&quality=80&width=320&height=320&dpr=1.5",
//         title: "Centro spaziale",
//         price: "59,99",
//         details: "Novità",
//         star: "5",
//       },
//       {
//         link: "https://www.lego.com/cdn/cs/set/assets/bltd53e79fa7920da2d/75547.jpg?fit=bounds&format=webply&quality=80&width=320&height=320&dpr=1.5",
//         title: "Shuttle dei Minion",
//         price: "189,99",
//         details: "Novità",
//         star: "5",
//       },
//       {
//         link: "https://www.lego.com/cdn/cs/set/assets/blt3dddc992e5559ddf/21309.jpg?fit=bounds&format=jpg&quality=80&width=320&height=320&dpr=1",
//         title: "Saturn V Apollo LEGO® NASA",
//         price: "199,99",
//         details: "Novità",
//         star: "5",
//       },
//     ],
//   ];

 export default apiDummy;